name: Project CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]  # Updated to newer versions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Updated to v3 for stability

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Generate Coverage Report
        run: npm run coverage
        continue-on-error: true  # Allow coverage to run even if tests fail

      - name: Upload Test Report
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: test-report
          path: coverage/
